# -*- coding: utf-8 -*-
"""15889//Yagnesh//CC7184.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xk5UXe47utGA2EbexsyJM4kSSijOE8Q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

df = pd.read_csv("ACS_Community_Partners_20250708.csv")

print(df.head())
print(df['BOROUGH'].value_counts())

def time_to_hours(t):
    try:
        if pd.isnull(t) or not isinstance(t, str):
            return 0
        t = t.strip().lower().replace("am", "").replace("pm", "")
        if ":" in t:
            hours, minutes = [int(x) for x in t.split(":")]
        else:
            hours = int(t)
            minutes = 0
        return hours + (minutes / 60)
    except:
        return 0

days = ['MON', 'TUES', 'WED', 'THURS', 'FRI']
weekly_hours = []
for _, row in df.iterrows():
    total = 0
    for day in days:
        from_time = time_to_hours(row.get(f'OFFICE_{day}_FROM_TIME'))
        to_time = time_to_hours(row.get(f'OFFICE_{day}_TO_TIME'))
        total += max(to_time - from_time, 0)
    weekly_hours.append(total)

df['WEEKLY_HOURS'] = weekly_hours

df = df.dropna(subset=['BOROUGH', 'LATITUDE', 'LONGITUDE'])

le = LabelEncoder()
df['BOROUGH_ENC'] = le.fit_transform(df['BOROUGH'])

df['LAT_BIN'] = df['LATITUDE'].round(2)
df['LON_BIN'] = df['LONGITUDE'].round(2)

features_sup = ['LAT_BIN', 'LON_BIN', 'WEEKLY_HOURS']
X = df[features_sup]
y = df['BOROUGH_ENC']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

log_model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
log_model.fit(X_train, y_train)
y_pred = log_model.predict(X_test)

print("\n--- Supervised: Logistic Regression ---")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

cv_scores = cross_val_score(log_model, X_scaled, y, cv=5)
print(f"Cross-Validation Accuracy (mean): {cv_scores.mean():.2f}")
print(f"Accuracy Std Dev: {cv_scores.std():.2f}")

features_unsup = ['LATITUDE', 'LONGITUDE', 'WEEKLY_HOURS']
X_unsup = df[features_unsup]

scaler_unsup = StandardScaler()
X_scaled_unsup = scaler_unsup.fit_transform(X_unsup)

silhouette_scores = []
for k in range(2, 10):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_scaled_unsup)
    silhouette_scores.append(silhouette_score(X_scaled_unsup, labels))

best_k = silhouette_scores.index(max(silhouette_scores)) + 2
print(f"\nOptimal K (clusters): {best_k}")

kmeans_final = KMeans(n_clusters=best_k, random_state=42, n_init=10)
df['CLUSTER'] = kmeans_final.fit_predict(X_scaled_unsup)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled_unsup)
df['PCA1'] = X_pca[:, 0]
df['PCA2'] = X_pca[:, 1]

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='PCA1', y='PCA2', hue='CLUSTER', palette='Set1')
plt.title('KMeans Clustering (PCA Projection)')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.legend(title='Cluster')
plt.show()

sil_score = silhouette_score(X_scaled_unsup, df['CLUSTER'])
print(f"Silhouette Score: {sil_score:.2f}")